os: Visual Studio 2017
version: 0.0.0.{build}

configuration:
- Debug
- Release

environment:
  matrix:
  - VS_VERSION: 14 2015
    VS_PLATFORM: win32
  - VS_VERSION: 14 2015
    VS_PLATFORM: x64
  - VS_VERSION: 15 2017
    VS_PLATFORM: win32
  - VS_VERSION: 15 2017
    VS_PLATFORM: x64

before_build:
- cd ..
- git clone -q --branch=master https://github.com/SuperSodaSea/Corecat.git
- cd Corecat
- git checkout -fq master
- xcopy include ..\Netycat\include /E /I /Q
- cd ..\Netycat
- cmake -H. -Bbuild -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM%

build:
  project: build/Netycat.sln
  parallel: true
  verbosity: minimal

test_script:
- build\%CONFIGURATION%\FileSystem_File.exe data\test1.txt test1.txt
- cat test1.txt
- build\%CONFIGURATION%\FileSystem_MappedFile.exe data\test1.txt test1.txt
- cat test1.txt
